Date cache service
hummingbird-project/hummingbird pull request #229
Opened 2023-08-19 10:31 UTC by adam-fowler

Convert Date Cache to a service

2023-08-25 14:57 UTC, Joannis commented
@adam-fowler can you set the base branch to `service-lifecycle-v2-beta` so that I can review these in isolation?

2023-08-25 15:09 UTC, adam-fowler commented
> @adam-fowler can you set the base branch to `service-lifecycle-v2-beta` so that I can review these in isolation?

Is it possible to change the base branch on a PR after it has been created?

2023-08-25 15:17 UTC, Joannis commented
Yeah you can. Just click on edit first, then change the base

2023-08-25 15:50 UTC, adam-fowler commented
> Yeah you can. Just click on edit first, then change the base

That's changed. You never used to be able to do that

2023-08-25 21:49 UTC, Joannis commented
@adam-fowler just a note. If #228 is merged, this base branch will change to whatever #228 merged into. So it'll change to 2.x.x automaticaly

2023-08-25 21:51 UTC, Joannis requested changes

2023-08-25 21:51 UTC, Joannis commented on Sources/Hummingbird/Application.swift
> +    public let dateCache: HBDateCache
Does this need to be `public`?

2023-08-25 21:51 UTC, Joannis commented on Sources/Hummingbird/Utils/DateCache.swift
> +            let timerSequence = AsyncTimerSequence(interval: .seconds(1), clock: .continuous)
This can be a `.suspending` clock. We don't hold a second counter ourselves, but request system time. So I think we should suspend.

2023-08-26 07:16 UTC, closed without merging

2023-08-26 07:41 UTC, adam-fowler commented
Squash and Merging the other branch closed this PR 😠