Update README for v2
hummingbird-project/hummingbird pull request #365
Opened 2024-01-29 18:54 UTC by adam-fowler

Updated links and removed a lot of unnecessary content

2024-01-30 07:16 UTC, tib requested changes
There is a small typo in this update.

2024-01-30 09:06 UTC, tib approved these changes

2024-01-30 09:09 UTC, Joannis commented on README.md
> +Hummingbird is a lightweight, flexible moderen web application framework that runs on top of a SwiftNIO based server implementation. It is designed to require the minimum number of dependencies.
```suggestion
Hummingbird is a lightweight, flexible modern web application framework that runs on top of a SwiftNIO based server implementation. It is designed to require the minimum number of dependencies.
```

2024-01-30 10:09 UTC, adam-fowler commented on README.md
> -| [HummingbirdWebSocket](https://github.com/hummingbird-project/hummingbird-websocket) | Adds support for WebSocket upgrade to server
No released build for 2.0 though. I can mention it I guess with the caveat there is no release.

2024-01-31 14:18 UTC, Joannis approved these changes

2024-01-31 16:06 UTC, merged