Optimise FlatDictionary init for scenarios where no values are stored and llow inlining access
hummingbird-project/hummingbird pull request #456
Opened 2024-05-19 20:36 UTC by Joannis

This provides specialized access to the type, and virtually eliminates its presence from routes where a flat dictionary is not used. This affects the route parameters primarily, but helps in particular because `CoreRequestContext` _always_ starts out with an empty `Parameters` instance.

2024-05-20 06:39 UTC, adam-fowler commented
Empty arrays don't allocate any memory, so I'm not sure this is going to be a saving, as you have added a branch whenever accessing the parameters now

2024-05-20 18:26 UTC, Joannis commented
I think my measurements are macOS-specific then.

2024-05-28 13:35 UTC, adam-fowler requested changes
Looks good, some minor change requests

2024-05-28 13:35 UTC, adam-fowler commented on Sources/HummingbirdCore/Utils/FlatDictionary.swift
> +        @usableFromInline internal /* private */ var elements: [Element]
Can we remove the commented out `/* private */` if we require everything to be `internal`

2024-05-28 13:35 UTC, adam-fowler commented on Sources/HummingbirdCore/Utils/FlatDictionary.swift
> +    public subscript(_ index: Index) -> Element { return self.storage!.elements[index] }
`!` isn't ideal here, perhaps we should add a precondition that `storage` exist and provide an out of range message or something similar, given the index will be out of range

2024-05-28 13:35 UTC, adam-fowler commented on Sources/HummingbirdCore/Utils/FlatDictionary.swift
> +    public func index(after index: Index) -> Index { index + 1 }
Any reason you changed this? I know `index+1` is correct in most cases, but what is the expected result when `index == endIndex`?

2024-05-28 13:35 UTC, adam-fowler commented on Sources/HummingbirdCore/Utils/FlatDictionary.swift
> +            if var storage, let index = storage.hashKeys.firstIndex(of: hashKey) {
The ordering of the if statements here is slightly confusing. Currently you test for the existence of storage twice when the key doesn't exist. Perhaps it should be 
```swift
if let storage {
    // do stuff when storage already exists
} else {
    // create storage if needed
}
```

2024-05-28 13:35 UTC, adam-fowler commented on Sources/HummingbirdCore/Utils/FlatDictionary.swift
> +extension FlatDictionary.Storage: Sendable where Key: Sendable, Value: Sendable {}
I added this in to get rid of a Sendable warning

2025-10-06 06:44 UTC, adam-fowler commented
@Joannis can I close this?

2026-04-12 23:01 UTC, closed without merging