Type erasing ResponseBodyWriter
hummingbird-project/hummingbird pull request #537
Opened 2024-09-05 11:38 UTC by adam-fowler

- Rename ResponseBodyWriter to ResponseBodyWriterProtocol
- Add type ResponseBodyWriter that holds an existential ResponseBodyWriterProtocol
- Broke code into three files to make it easier to read

2024-09-05 13:09 UTC, sliemeobn reviewed
nice!

I think this provides a nicer API for "users" of `ReponseBody` and more ergonomic extensions of it (ie: `ResponseBodyWriter` can now conform to protocols)

not 100% sure I like the naming of `ResponseBodyWriterProtocol`. this will only affect implementers of a ResponseBodyWriter, but it might be potentially confusing.

in the olden days words like `ResponseBodyWriting` were used, but it seems this is falling out of favor 🤔

2024-09-05 19:51 UTC, Joannis requested changes
I understand the desire for this change, and I like it a lot. But I don't think that the value provided by this change outweighs a breaking change so late in the RC phase.

I'm happy to be convinced otherwise, maybe if more people weigh in

2024-09-06 06:07 UTC, adam-fowler commented
Another option is I ditch all the API breaking changes and simply add a `AnyResponseBodyWriter` type which the user can use in their own code.

2024-09-08 12:52 UTC, MahdiBM commented on Sources/HummingbirdCore/Response/ResponseBodyWriter.swift
> +    public var wrapped: any ResponseBodyWriterProtocol
I wonder if sometime in the future you'd want to make an special case for hummingbird's own response-body-writer with an enum, for performance optimizations.

Just something to keep in mind. This public var shouldn't stop use from doing that.

2024-09-08 13:01 UTC, MahdiBM commented on Sources/HummingbirdCore/Response/ResponseBodyWriter.swift
> +    public var wrapped: any ResponseBodyWriterProtocol
(Like `NIOAny`, or even String's own "guts")

2024-09-08 16:02 UTC, adam-fowler commented
Both protocol and type erased type need to be available. Users need to be able to write their own Response body writers. This new type fulfills the need for a concrete type that can be extended.

2024-09-09 18:00 UTC, adam-fowler commented
I've decided to not go ahead with this PR.

2024-09-09 18:00 UTC, closed without merging